// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/Footer.vue')['default']
    README: typeof import('./src/components/README.md')['default']
    DropdownButton: typeof import('./src/components/atoms/DropdownButton.vue')['default']
    DropdownOption: typeof import('./src/components/atoms/DropdownOption.vue')['default']
    DropdownOptions: typeof import('./src/components/atoms/DropdownOptions.vue')['default']
    GlassPanel: typeof import('./src/components/atoms/GlassPanel.vue')['default']
    MicrowaveTime: typeof import('./src/components/atoms/MicrowaveTime.vue')['default']
    StepPanel: typeof import('./src/components/atoms/StepPanel.vue')['default']
    Toggle: typeof import('./src/components/atoms/Toggle.vue')['default']
    Dropdown: typeof import('./src/components/molecules/Dropdown.vue')['default']
    ConverterGroup: typeof import('./src/components/organisms/ConverterGroup.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    CarbonCampsite: typeof import('virtual:vite-icons/carbon/campsite')['default']
    CarbonMoon: typeof import('virtual:vite-icons/carbon/moon')['default']
    CarbonSun: typeof import('virtual:vite-icons/carbon/sun')['default']
    CarbonLanguage: typeof import('virtual:vite-icons/carbon/language')['default']
    CarbonDicomOverlay: typeof import('virtual:vite-icons/carbon/dicom-overlay')['default']
    CarbonLogoGithub: typeof import('virtual:vite-icons/carbon/logo-github')['default']
  }
}

export { }
