<template>
  <ListboxButton
    v-slot="{ open }"
    class="
      <==BUTTON==>
      <!--📦️-->
      relative
      block
      w-full
      p-0
      <!--👇-->
      group
      focus:outline-none
      cursor-pointer
    "
  >
    <span
      class="
        <==BUTTON__SHADOW==>
        <!--📦️-->
        absolute
        inset-0
        <!--💄-->
        rounded-2xl
        bg-gray-300
        translate-y-0.5
        blur-sm
        <!--🚀-->
        will-transform
        transition-transform
        duration-600
        ease-button-cubic-1
        <!--👇-->
        group-hover:translate-y-1
        group-hover:duration-250
        group-focus-visible:translate-y-1
        group-focus-visible:duration-250
      "
    ></span>
    <span
      class="
        <==BUTTON__EDGE==>
        <!--📦️-->
        absolute
        inset-0
        <!--💄-->
        bg-button-edge
        rounded-2xl
      "
    >
    </span>
    <span
      class="
        <==BUTTON__FR0NT==>
        <!--📦️-->
        block
        py-2
        pl-6
        pr-12
        sm:py-3
        sm:pl-8
        sm:pr-14
        -translate-y-1.5
        <!--💄-->
        bg-white
        border-2 border-gray-100
        rounded-2xl
        <!--🚀-->
        will-transform
        transition-transform
        duration-600
        ease-button-cubic-1
        <!--👇-->
        group-hover:-translate-y-2
        group-hover:duration-250
        group-hover:ease-button-cubic-2

        group-focus-visible:-translate-y-2
        group-focus-visible:duration-250
        group-focus-visible:ease-button-cubic-2

        group-active:-translate-y-0.5
        group-active:duration-34
      "
      :class="
        open
          ? 'ease-button-cubic-2 duration-34 -translate-y-0.5 group-hover:-translate-y-0.5'
          : ``
      "
    >
      <slot></slot>
    </span>
  </ListboxButton>
</template>
