<template>
  <ListboxButton
    class="
      <==BUTTON==>
      <!--📦️-->
      relative
      block
      w-full
      p-0
      <!--👇-->
      group
      focus:outline-none
      cursor-pointer
    "
  >
    <span
      class="
        <==BUTTON__SHADOW==>
        <!--📦️-->
        absolute
        inset-0
        <!--💄-->
        rounded-full
        bg-gray-300
        translate-y-0.5
        filter
        blur-sm
        <!--🚀-->
        will-transform
        transition-transform
        duration-600
        ease-button-cubic-1
        <!--👇-->
        group-hover:translate-y-1
        group-hover:duration-250
        group-focus-visible:translate-y-1
        group-focus-visible:duration-250
      "
    ></span>
    <span
      class="
        <==BUTTON__EDGE==>
        <!--📦️-->
        absolute
        inset-0
        <!--💄-->
        bg-button-edge
        rounded-full
      "
    >
    </span>
    <span
      class="
        <==BUTTON__FR0NT==>
        <!--📦️-->
        relative
        block
        w-full
        py-2
        px-6
        sm:px-8
        sm:py-3
        -translate-y-1
        <!--💄-->
        bg-white
        border-2 border-gray-100
        rounded-full
        <!--🚀-->
        will-transform
        transition-transform
        duration-600
        ease-button-cubic-1
        <!--👇-->
        group-hover:-translate-y-1.5
        group-hover:duration-250
        group-hover:ease-button-cubic-2
        group-focus-visible:-translate-y-0.5
        group-focus-visible:duration-34
        group-active:duration-34
        group-active:-translate-y-0.5
      "
    >
      <slot></slot>
    </span>
  </ListboxButton>
</template>

<script setup lang="ts">
import { ListboxButton } from "@headlessui/vue"
</script>
